//
//	ChevronBreadcrumbButton.h
//	New Image
//
//	Created by Jonathan Saggau on 8/4/10
//	Copyright 2010 Sounds Broken inc
//	This code was generated by Opacity. You may use or modify it in any way.
//

#import <UIKit/UIKit.h>

extern const CGFloat kMyViewWidth;
extern const CGFloat kMyViewHeight;

@interface MyView : UIView

@end
